version: '3'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.15.2
    environment:
      - discovery.type=single-node
      - ELASTIC_PASSWORD=aoeidrns
      - xpack.security.enabled=false
      - xpack.security.http.ssl.enabled=false

    ports:
      - 9200:9200
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data
      - ./certs:/usr/share/elasticsearch/config/certs
    mem_limit: 2g

volumes:
  elasticsearch-data:
